import AppKit

public enum ClipboardPrivacy {
    public static let ignoredPasteboardTypeIdentifiers: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]

    public static func shouldIgnore(_ pasteboard: NSPasteboard) -> Bool {
        let declaredTypes = pasteboard.pasteboardItems?.flatMap(\.types)
            ?? pasteboard.types
            ?? []
        let declaredTypeIdentifiers = Set(declaredTypes.map(\.rawValue))
        return !ignoredPasteboardTypeIdentifiers.isDisjoint(with: declaredTypeIdentifiers)
    }
}
