import AppKit
import CPasteCore

func testSensitiveAndTransientPasteboardTypesAreIgnored() {
    let ignoredTypeIdentifiers = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb"
    ]

    for identifier in ignoredTypeIdentifiers {
        if identifier == "Pasteboard generator type" {
            check(
                ClipboardPrivacy.ignoredPasteboardTypeIdentifiers.contains(identifier),
                "legacy pasteboard generator marker should remain ignored"
            )
            continue
        }

        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }

        let item = NSPasteboardItem()
        check(item.setString("secret value", forType: .string), "secret fixture should contain text")
        check(
            item.setString("1", forType: NSPasteboard.PasteboardType(identifier)),
            "secret fixture should contain privacy marker \(identifier)"
        )
        check(pasteboard.writeObjects([item]), "secret fixture should be written to named pasteboard")
        check(
            PasteboardReader.read(from: pasteboard) == nil,
            "pasteboard type \(identifier) should be ignored"
        )
    }
}
